name: Build and push 'standard pandoc image' to Docker

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
  workflow_dispatch: {}

env:
  DTC_VERSION: v3.1.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: alpine-with-pandoc
          build-args: DTC_VERSION=${{ env.DTC_VERSION }}
          load: true
          # TODO Make tag/version dependent on branch (push normal version only when on main branch, otherwise derive temporary version from branch name/datetime/commit-id/...)
          tags: doctoolchain/doctoolchain-with-pandoc:${{ env.DTC_VERSION }}
      -
        name: Test Image
        run: |
          docker run \
            --rm \
            -v ${PWD}/test:/workspace \
            -w /workspace \
            doctoolchain/doctoolchain-with-pandoc:${{ env.DTC_VERSION }} \
            bash -c "set -eu; test -w /etc/environment && ls -l /etc/environment; doctoolchain . tasks"
      -
        name: Push Image
        uses: docker/build-push-action@v3
        with:
          context: alpine-with-pandoc
          push: true
          tags: doctoolchain/doctoolchain-with-pandoc:${{ env.DTC_VERSION }}
