name: Build and push 'standard image' to Docker

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch: {}

env:
  DTC_VERSION: v3.1.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: echo "build"

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: echo "build"


  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build, test]
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: echo "build"
